Repository watual/LunchRecommender, pull requests merged in 2024-06, with the labels that each got.

#10 Feat/post get
  .gradle/8.7/checksums/checksums.lock
  .gradle/8.7/dependencies-accessors/gc.properties
  .gradle/8.7/executionHistory/executionHistory.lock
  .gradle/8.7/fileChanges/last-build.bin
  .gradle/8.7/fileHashes/fileHashes.lock
  .gradle/8.7/gc.properties
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/cache.properties
  .gradle/vcs-1/gc.properties
  build.gradle
  src/main/java/com/sparta/lunchrecommender/controller/PostController.java
  src/main/java/com/sparta/lunchrecommender/controller/Test.java
  src/main/java/com/sparta/lunchrecommender/dto/PostResponseDto.java
  src/main/java/com/sparta/lunchrecommender/entity/Post.java
  src/main/java/com/sparta/lunchrecommender/entity/Timestamped.java
  src/main/java/com/sparta/lunchrecommender/entity/TmpUser.java
  src/main/java/com/sparta/lunchrecommender/repository/PostRepository.java
  src/main/java/com/sparta/lunchrecommender/repository/TmpUserRepository.java
  src/main/java/com/sparta/lunchrecommender/service/PostService.java
  src/main/java/com/sparta/lunchrecommender/service/Test.java
  src/main/resources/application.properties
Labels: enhancement

#12 feat : 게시물 작성 기능 구현
  src/main/java/com/sparta/lunchrecommender/LunchrecommenderApplication.java
  src/main/java/com/sparta/lunchrecommender/config/TestConfig.java
  src/main/java/com/sparta/lunchrecommender/constant/TestConstant.java
  src/main/java/com/sparta/lunchrecommender/controller/PostController.java
  src/main/java/com/sparta/lunchrecommender/dto/Test.java
  src/main/java/com/sparta/lunchrecommender/dto/post/PostCreateRequestDto.java
  src/main/java/com/sparta/lunchrecommender/dto/post/PostResponseDto.java
  src/main/java/com/sparta/lunchrecommender/entity/Post.java
  src/main/java/com/sparta/lunchrecommender/entity/Test.java
  src/main/java/com/sparta/lunchrecommender/entity/TmpUser.java
  src/main/java/com/sparta/lunchrecommender/entity/TmpUserJH.java
  src/main/java/com/sparta/lunchrecommender/error/Test.java
  src/main/java/com/sparta/lunchrecommender/filter/Test.java
  src/main/java/com/sparta/lunchrecommender/jwt/Test.java
  src/main/java/com/sparta/lunchrecommender/repository/Test.java
  src/main/java/com/sparta/lunchrecommender/repository/TmpUserRepository.java
  src/main/java/com/sparta/lunchrecommender/repository/TmpUserRepositoryJH.java
  src/main/java/com/sparta/lunchrecommender/service/PostService.java
Labels: enhancement

#14 feat : 게시물 수정 기능 구현
  src/main/java/com/sparta/lunchrecommender/LunchrecommenderApplication.java
  src/main/java/com/sparta/lunchrecommender/controller/PostController.java
  src/main/java/com/sparta/lunchrecommender/dto/post/PostUpdateRequestDto.java
  src/main/java/com/sparta/lunchrecommender/entity/Post.java
  src/main/java/com/sparta/lunchrecommender/service/PostService.java
Labels: enhancement

#16 [FEATURE] 프로필조회
  src/main/java/com/sparta/lunchrecommender/controller/ProfileController.java
  src/main/java/com/sparta/lunchrecommender/dto/profile/ProfileRequestDto.java
  src/main/java/com/sparta/lunchrecommender/dto/profile/ProfileResponseDto.java
  src/main/java/com/sparta/lunchrecommender/entity/TmpUserSM.java
  src/main/java/com/sparta/lunchrecommender/repository/TmpUserSMRepository.java
  src/main/java/com/sparta/lunchrecommender/service/ProfileService.java
Labels: enhancement

#19 [FEATURE] 프로필 수정기능
  src/main/java/com/sparta/lunchrecommender/controller/ProfileController.java
  src/main/java/com/sparta/lunchrecommender/entity/TmpUserSM.java
  src/main/java/com/sparta/lunchrecommender/service/ProfileService.java
Labels: enhancement

#21 feat : 댓글 작성 기능 구현
  .gradle/8.7/checksums/checksums.lock
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  build.gradle
  src/main/java/com/sparta/lunchrecommender/controller/CommentController.java
  src/main/java/com/sparta/lunchrecommender/dto/comment/CommentRequestDto.java
  src/main/java/com/sparta/lunchrecommender/dto/comment/CommentResponseDto.java
  src/main/java/com/sparta/lunchrecommender/entity/Comment.java
  src/main/java/com/sparta/lunchrecommender/repository/CommentRepository.java
  src/main/java/com/sparta/lunchrecommender/service/CommentService.java
  src/main/resources/application.properties
Labels: enhancement

#18 feat : 게시물 삭제 기능 구현
  src/main/java/com/sparta/lunchrecommender/controller/PostController.java
  src/main/java/com/sparta/lunchrecommender/service/PostService.java
Labels: enhancement

#24 [BUG] 로그인 & [FEATURE] 유효성 검사, 성공 및 실패 응답 추가
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  build.gradle
  src/main/java/com/sparta/lunchrecommender/controller/UserController.java
  src/main/java/com/sparta/lunchrecommender/dto/HttpResponseDto.java
  src/main/java/com/sparta/lunchrecommender/dto/user/LoginRequestDto.java
  src/main/java/com/sparta/lunchrecommender/dto/user/UserRequestDto.java
  src/main/java/com/sparta/lunchrecommender/security/JwtAuthenticationFilter.java
  src/main/java/com/sparta/lunchrecommender/security/Test.java
Labels: bug, enhancement

#32 feat : 댓글 조회 기능 구현
  src/main/java/com/sparta/lunchrecommender/controller/CommentController.java
  src/main/java/com/sparta/lunchrecommender/dto/comment/CommentResponseDto.java
  src/main/java/com/sparta/lunchrecommender/entity/Comment.java
  src/main/java/com/sparta/lunchrecommender/repository/CommentRepository.java
  src/main/java/com/sparta/lunchrecommender/service/CommentService.java
  src/main/resources/application.yml
Labels: enhancement

#34 [FEATURE] 댓글 수정 기능 구현
  src/main/java/com/sparta/lunchrecommender/controller/CommentController.java
  src/main/java/com/sparta/lunchrecommender/entity/Comment.java
  src/main/java/com/sparta/lunchrecommender/service/CommentService.java
Labels: enhancement

#33 refactor : 게시물 작성
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  src/main/java/com/sparta/lunchrecommender/controller/PostController.java
  src/main/java/com/sparta/lunchrecommender/controller/UserController.java
  src/main/java/com/sparta/lunchrecommender/dto/post/PostResponseDto.java
  src/main/java/com/sparta/lunchrecommender/entity/Post.java
  src/main/java/com/sparta/lunchrecommender/entity/User.java
  src/main/java/com/sparta/lunchrecommender/service/PostService.java
Labels: enhancement

#37 refactor : 게시물 조회 수정
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  src/main/java/com/sparta/lunchrecommender/controller/PostController.java
Labels: duplicate

#38 update : 데이터 전체조회 허용
  src/main/java/com/sparta/lunchrecommender/config/WebSecurityConfig.java
  src/main/java/com/sparta/lunchrecommender/controller/PostController.java
Labels: enhancement

#40 [FEATURE] 좋아요 기능추가
  src/main/java/com/sparta/lunchrecommender/constant/ContentsTypeEnum.java
  src/main/java/com/sparta/lunchrecommender/controller/LikeController.java
  src/main/java/com/sparta/lunchrecommender/dto/like/LikeRequestDto.java
  src/main/java/com/sparta/lunchrecommender/entity/Like.java
  src/main/java/com/sparta/lunchrecommender/repository/LikeRepository.java
  src/main/java/com/sparta/lunchrecommender/service/LikeService.java
Labels: enhancement

#43 update : 게시물 수정 토큰 검사
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  src/main/java/com/sparta/lunchrecommender/controller/PostController.java
  src/main/java/com/sparta/lunchrecommender/dto/post/PostResponseDto.java
  src/main/java/com/sparta/lunchrecommender/service/PostService.java
Labels: duplicate

#45 ADD : 댓글 삭제 기능 구현
  src/main/java/com/sparta/lunchrecommender/controller/CommentController.java
  src/main/java/com/sparta/lunchrecommender/service/CommentService.java
Labels: enhancement

#46 UPDATE : 게시물 삭제 토큰 검사
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  src/main/java/com/sparta/lunchrecommender/controller/PostController.java
  src/main/java/com/sparta/lunchrecommender/service/PostService.java
Labels: duplicate

#47 FIX : 프로필 조회/수정에 유저 인증추가
  src/main/java/com/sparta/lunchrecommender/controller/ProfileController.java
  src/main/java/com/sparta/lunchrecommender/dto/profile/ProfileRequestDto.java
  src/main/java/com/sparta/lunchrecommender/dto/profile/ProfileResponseDto.java
  src/main/java/com/sparta/lunchrecommender/entity/TmpUserSM.java
  src/main/java/com/sparta/lunchrecommender/entity/User.java
  src/main/java/com/sparta/lunchrecommender/repository/TmpUserSMRepository.java
  src/main/java/com/sparta/lunchrecommender/service/ProfileService.java
Labels: enhancement

#54 FEAT : 좋아요 수 조회
  src/main/java/com/sparta/lunchrecommender/controller/LikeController.java
  src/main/java/com/sparta/lunchrecommender/dto/like/LikeResponseDto.java
  src/main/java/com/sparta/lunchrecommender/service/LikeService.java
Labels: enhancement

#57 FEAT : 페이지네이션 기능 구현
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  src/main/java/com/sparta/lunchrecommender/controller/CommentController.java
  src/main/java/com/sparta/lunchrecommender/controller/PostController.java
  src/main/java/com/sparta/lunchrecommender/entity/Comment.java
  src/main/java/com/sparta/lunchrecommender/entity/Post.java
  src/main/java/com/sparta/lunchrecommender/repository/PostRepository.java
  src/main/java/com/sparta/lunchrecommender/service/LikeService.java
  src/main/java/com/sparta/lunchrecommender/service/PostService.java
Labels: enhancement

#62 FEATURE : 팔로우/언팔로우 기능 구현
  src/main/java/com/sparta/lunchrecommender/controller/FollowController.java
  src/main/java/com/sparta/lunchrecommender/dto/follow/FollowRequestDto.java
  src/main/java/com/sparta/lunchrecommender/entity/Follow.java
  src/main/java/com/sparta/lunchrecommender/repository/FollowRepository.java
  src/main/java/com/sparta/lunchrecommender/service/FollowService.java
Labels: enhancement

#68 [REFACTOR] controller 반환 값 수정, [ADD] SwaggerConfig 추가
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  src/main/java/com/sparta/lunchrecommender/domain/auth/controller/AuthController.java
  src/main/java/com/sparta/lunchrecommender/domain/comment/controller/CommentController.java
  src/main/java/com/sparta/lunchrecommender/domain/follow/controller/FollowController.java
  src/main/java/com/sparta/lunchrecommender/domain/like/controller/LikeController.java
  src/main/java/com/sparta/lunchrecommender/domain/post/controller/PostController.java
  src/main/java/com/sparta/lunchrecommender/domain/user/controller/ProfileController.java
  src/main/java/com/sparta/lunchrecommender/domain/user/controller/UserController.java
  src/main/java/com/sparta/lunchrecommender/domain/user/service/UserService.java
  src/main/java/com/sparta/lunchrecommender/global/config/SwaggerConfig.java
  src/main/java/com/sparta/lunchrecommender/global/dto/HttpResponseDto.java
  src/main/resources/application.yml
Labels: enhancement

#69 BUG : likecount 초기값 지정
  src/main/java/com/sparta/lunchrecommender/domain/comment/entity/Comment.java
  src/main/java/com/sparta/lunchrecommender/domain/like/entity/Like.java
  src/main/java/com/sparta/lunchrecommender/domain/post/entity/Post.java
Labels: bug
